version: '3'

services:
  frontend:
    build: ./react-frontend
    volumes:
      - ./react-frontend/app/src/:/app/src
  backend:
    build: ./flask-backend
    volumes:
      - ./flask-backend/app:/app
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
#    depends_on:
#      - db
  db:
    image: mongo:3.6
    volumes:
      - ./db/initdb.js:/docker-entrypoint-initdb.d/initdb.js
    ports:
      - 27017:27017
  proxy:
    image: nginx:1.12.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8000:8000
    depends_on:
      - frontend
      - backend
